### ISSUE TITLE
Build is broken with latest v

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/rmb#18]
Using latest V to build messagebus eventually leads to:

```
/root/.vmodules/threefoldtech/rmb/server/server.v:190:28: error: cannot assign to `update.epoch`: expected `int`, not `i64`
  188 |     // remove one retry
  189 |     update.retry -= 1
  190 |     update.epoch = time.now().unix_time()
      |                               ~~~~~~~~~~~
  191 | 
  192 |     value := json.encode(update)
```

**Comment by maxux** [comment]
@xmonader already had this issue and and fixed it AFAIK

**Comment by LeeSmet** [comment]
This was encountered running the build script in a docker (slighlty modified since I use an ubuntu) just now :shrug:

**Comment by maxux** [comment]
Fixed via https://github.com/threefoldtech/rmb/commit/edeaabfad0494914222df0f10284a978b4a0dcdc
